version: '3'

services: 
    location-api:
        build: ./src/LocationApi
        ports: 
            - 5000:80
        networks: 
            - dotnetcorepromgrafana

    people-api:
        build: ./src/PeopleApi
        ports: 
            - 5001:80
        networks: 
            - dotnetcorepromgrafana
    
    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus:/etc/prometheus
            # - //d/docker/prometheus:/etc/prometheus
        networks:
            - dotnetcorepromgrafana
            
    grafana: 
        image: grafana/grafana
        depends_on:
            - prometheus
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=abcABC123
        ports:
            - 3000:3000
        volumes: 
            - ./grafana:/var/lib/grafana
        networks:
            - dotnetcorepromgrafana
        
networks: 
    dotnetcorepromgrafana:
